modLoader = "javafml"
loaderVersion = "[9,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "base_bridge"
version = "${version}"
displayName = "Base Bridge"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.base_bridge]]
modId = "neoforge"
type = "required"
ordering = "NONE"
side = "BOTH"

[[dependencies.base_bridge]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5,1.21.8]"
ordering = "NONE"
side = "BOTH"

[[dependencies.base_bridge]]
modId = "architectury"
type = "required"
ordering = "AFTER"
side = "BOTH"

[[dependencies.base_bridge]]
modId="kriforfab"
type = "required"
mandatory = true
ordering="NONE"
side="BOTH"

[[mixins]]
config = "base_bridge.mixins.json"

[[mixins]]
config = "base_bridge.neoforge.mixins.json"
