modLoader = "javafml"
loaderVersion = "[9,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "base_bridge"
version = "${version}"
displayName = "Base Bridge"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.base_bridge]]
modId = "neoforge"
type = "required"
versionRange = "[21.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.base_bridge]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.base_bridge]]
modId = "architectury"
type = "required"
versionRange = "[17.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "base_bridge.mixins.json"

[[mixins]]
config = "base_bridge.neoforge.mixins.json"
